import { DuringContent } from '../during/content';
import { DuringTrigger } from '../during/trigger';
import { InstantContent } from '../instant/content';
import { InstantTrigger } from '../instant/trigger';
import { OpeningContent } from '../opening';
import { Precondition } from '../precondition';
import { AbilityTrigger } from '../types';
import { Container } from './container';
export declare class Difference {
    differentThreshold: boolean;
    differentStrength: boolean;
    differentPreconditionThreshold: boolean;
    differentFrame: boolean;
    abi1: AbilityTrigger;
    abi2: AbilityTrigger;
    container: Container;
    constructor(abi1: AbilityTrigger, abi2: AbilityTrigger, container: Container);
    surroundIfDiff(param1: boolean, param2: string): string;
    notEqualsFloat(param1: number, param2: number): boolean;
    diffPrecondition(param1: Precondition, param2: Precondition): void;
    diffOpeningContentAbilityKind(param1: OpeningContent, param2: OpeningContent): void;
    diffInstantTrigger(param1: InstantTrigger, param2: InstantTrigger): void;
    diffInstantContent(param1: InstantContent, param2: InstantContent): void;
    diffInstantBattleAbilityTriggerKind(param1: InstantTrigger, param2: InstantTrigger): void;
    diffInstantAbilityInstantCharacterContent(param1: InstantContent, param2: InstantContent): void;
    diffInstantAbilityInstantBattleContent(param1: InstantContent, param2: InstantContent): void;
    diffInstantAbilityDurationTimeCharacterContent(param1: InstantContent, param2: InstantContent): void;
    diffInstant(param1: Required<AbilityTrigger>, param2: Required<AbilityTrigger>): void;
    diffInitialAbilityTriggerKind(param1: Precondition | InstantTrigger, param2: Precondition | InstantTrigger, param3: boolean): void;
    diffDuringTrigger(param1: Precondition | DuringTrigger, param2: Precondition | DuringTrigger, param3: boolean): void;
    diffDuringCharacterAbilityTriggerKind(param1: Precondition | DuringTrigger, param2: Precondition | DuringTrigger, param3: boolean): void;
    diffDuringBattleAbilityTriggerKind(param1: Precondition | DuringTrigger, param2: Precondition | DuringTrigger): void;
    diffDuring(param1: Required<AbilityTrigger>, param2: Required<AbilityTrigger>): void;
    diffConditionChangeContent(param1: DuringContent, param2: DuringContent): void;
    diffCommonAbilityContent(param1: InstantContent | DuringContent, param2: InstantContent | DuringContent): void;
    diffCommonAbilityBattleContent(param1: InstantContent | DuringContent, param2: InstantContent | DuringContent): void;
    convertThreshold(param1: string, param2: boolean): string;
    convertStrength(param1: string): string;
    convertFrame(param1: string): string;
}
