import { Content } from '../common/content';
import { Target } from '../common/target';
import { TriggerPuller } from '../common/trigger';
import { DuringContent } from '../during/content';
import { DuringTrigger } from '../during/trigger';
import { InstantContent } from '../instant/content';
import { InstantTrigger } from '../instant/trigger';
import { Opening } from '../opening';
import { Precondition } from '../precondition';
import { Container } from './container';
export declare class Stringfy {
    container: Container;
    level: 1 | 2 | 3 | 4 | 5;
    constructor(strings: Container, level?: 1 | 2 | 3 | 4 | 5);
    stringfyVarietyTrigger(param1: string, threshold: number, limit: number | undefined, _param4: boolean): string;
    stringfyVarietyKind(param1: string): string;
    stringfyUnisonable(param1: boolean): string;
    stringfyUnisonMyselfTrigger(group: Array<string>, target: Target | undefined): string;
    stringfyTriggerPuller(param1: TriggerPuller, param2: boolean): string;
    stringfyThirdCharacterTrigger(group: Array<string>): string;
    stringfyStrengthTimes(num?: number): string;
    stringfyStrengthPercentUpDownForTrigger(num: number | undefined, _param2: boolean): string;
    stringfyStrengthPercentUpDown(num?: number): string;
    stringfyStrengthPercentForTrigger(num: number | undefined, _param2: boolean): string;
    stringfyStrengthPercent(num?: number): string;
    stringfySecondDuring(second: number | undefined): string;
    stringfySecondCharacterTrigger(group: Array<string>): string;
    stringfySecond(second: number | undefined): string;
    stringfyPrefixTriggerLimit(limit: number | undefined, param2: boolean): string;
    stringfyPreconditionAndDuringTrigger(precondition: Precondition, trigger: DuringTrigger, target: Target | undefined): string;
    stringfyPrecondition(precondition: Precondition, target: Target | undefined): string;
    stringfyPercentUpDown(num?: number): string;
    stringfyPercentNormal(num?: number): string;
    stringfyPercent(num?: number): string;
    stringfyParameterReference(param1: string): string;
    stringfyOpening(param1: Opening): string;
    stringfyMyselfTrigger(group: Array<string>, target: Target | undefined): string;
    stringfyMemberTrigger(group: Array<string>, threshold: number, limit: number | undefined, _param4: boolean): string;
    stringfyMaxStrengthPercent(partial: string, limit: number | undefined, param3: boolean, threshold: number | undefined): string;
    stringfyMaxStrengthCount(partial: string, limit: number | undefined, param3: boolean, threshold: number | undefined): string;
    stringfyMaxAccumulationPercent(param1: string, param2: number | undefined, param3: number | undefined): string;
    stringfyMaxAccumulationCount(param1: string, param2: number | undefined, param3: number | undefined): string;
    stringfyLeaderCharacterTrigger(group: Array<string>): string;
    stringfyLeaderTrigger(target: Target | undefined): string;
    stringfyInstantTriggerOneOfEnemyCondition(): string;
    stringfyInstantTriggerOneOfEnemyCharacterCount(): string;
    stringfyInstantTriggerInitial(param1: number, param2: InstantTrigger | Precondition, param3: boolean, param4: Target | undefined): string;
    stringfyInstantTriggerHpLow(param1: TriggerPuller, threshold: number | undefined, limit: number | undefined, target: Target | undefined): string;
    stringfyInstantTriggerHealHigh(param1: TriggerPuller, threshold: number | undefined, limit: number | undefined, target: Target | undefined): string;
    stringfyInstantTriggerEnemyCondition(param1: InstantTrigger, threshold: number | undefined, limit: number | undefined, param4: boolean): string;
    stringfyInstantTriggerElapsedTime(threshold: number | undefined, limit: number | undefined): string;
    stringfyInstantTriggerCount(param1: string, threshold: number | undefined, limit: number | undefined, param4: boolean): string;
    stringfyInstantTriggerCondition(param1: TriggerPuller | undefined, param2: InstantTrigger, threshold: number | undefined, limit: number | undefined, param5: boolean, target: Target | undefined): string;
    stringfyInstantTriggerCombo(threshold: number | undefined, param2: string, limit: number | undefined): string;
    stringfyInstantTriggerCharacterCount(kind: string, threshold: number | undefined, limit: number | undefined, param4: TriggerPuller | undefined, param5: boolean, target: Target | undefined, _param7: boolean): string;
    stringfyInstantTriggerBattle(param1: InstantTrigger, param2: TriggerPuller | undefined, target: Target | undefined): string;
    stringfyInstantTrigger(param1: InstantTrigger, target: Target | undefined): string;
    stringfyInstantContent(content: Content, isInitialTrigger: boolean, limit: number | undefined, notFirst: boolean): string;
    stringfyInstantCharacterContent(param1: Content, param2: Content, isInitialTrigger: boolean, limit: number | undefined, notFirst: boolean): string;
    stringfyInstantBattleContent(param1: Content, isInitialTrigger: boolean, limit: number | undefined): string;
    stringfyInitialWithoutContinuation(): string;
    stringfyFlipLimitOrFrame(limit: number | undefined, frame: number | undefined): string;
    strinfyElementTarget(param1: string): string;
    stringfyElementShort(param1: string): string;
    stringfyElementFull(param1: string): string;
    stringfyDuringTriggerCondition(param1: TriggerPuller | undefined, param2: DuringTrigger | InstantTrigger, threshold: number | undefined, _param4: boolean, param5: Target | undefined): string;
    stringfyDuringTrigger(param1: DuringTrigger, param2: boolean, target: Target | undefined): string;
    stringfyDuringCharacterTrigger(param1: TriggerPuller, param2: DuringTrigger, param3: boolean, target: Target | undefined): string;
    stringfyDuringBattleTrigger(param1: DuringTrigger, _param2: boolean, param3: Target | undefined): string;
    stringfyDurationTimeCharacterContent(param1: Content, param2: Content, frame: number | undefined, limit: number | undefined, notFirst: boolean): string;
    stringfyCountUp(threshold: number | undefined, _param2?: boolean): string;
    stringfyCountDown(threshold: number | undefined, _param2?: boolean): string;
    stringfyCount(threshold: number | undefined, _param2: boolean): string;
    stringfyConjuctionTriggerLimit(param1?: number): string;
    stringfyCondtionTarget(param1: DuringTrigger | InstantTrigger | DuringContent | InstantContent, isTargetEnemy: boolean): string;
    stringfyConditionShareTarget(param1: string): string;
    stringfyConditionCharacterContent(param1: Content, param2: Content, frame: number | undefined, limit: number | undefined, notFirst: boolean): string;
    stringfyConditionBattleContent(param1: Content, frame: number | undefined, limit: number | undefined): string;
    stringfyCommonContent(param1: Content, limit: number | undefined, notFirst?: boolean): string;
    stringfyCommonCharacterContent(param1: Content, param2: Content, limit: number | undefined, notFirst?: boolean): string;
    stringfyCommonBattleContent(param1: Content, limit: number | undefined): string;
    stringfyCharacterGroups(characterGroups: Array<string>, isTargetEnemy: boolean): string;
    stringfyCharacterAtTrigger(param1: string, param2: Array<string>): string;
    stringfyBattleCountUp(param1: string, threshold: number | undefined): string;
    stringfyAlways(param1: number): string;
    stringfyAdditionalDirectAttack(param1: InstantContent | DuringContent, param2: Content, notFirst: boolean): string;
    stringfyAbilityTarget(content: Content): string;
    isTriggerPullerOmittable(kind: string, target: Target | undefined, param3: boolean): boolean;
    isInitialTrigger(param1: InstantTrigger): boolean;
    isContinuationInstantContent(param1: Content): boolean;
    isContinuationInstantCharacterContent(param1: Content): boolean;
    isContinuationInstantBattleContent(param1: Content): boolean;
    getWithTriggerPullerAndTimes(id: string, param2: TriggerPuller, param3: number | undefined, param4: boolean, param5: Target | undefined): string;
    getWithTriggerPullerAndPercent(id: string, param2: TriggerPuller, param3: number | undefined, param4: boolean, param5: boolean, param6: Target | undefined): string;
    getWithTriggerPullerAndConditionTarget(id: string, param2: TriggerPuller, param3: DuringTrigger | InstantTrigger, param4: boolean, param5: Target | undefined): string;
    getWithTriggerPuller(id: string, param2: TriggerPuller, param3: boolean, param4: Target | undefined): string;
    getWithTimesAndLevel(id: string, level: number, limit: number | undefined): string;
    getWithTimes(id: string, limit: number | undefined): string;
    getWithTargetAndStrengthCountUp(id: string, content: Content, threshold: number | undefined): string;
    getWithTargetAndStrengthCountDown(id: string, content: Content, threshold: number | undefined): string;
    getWithTargetAndStrengthCount(id: string, content: Content, threshold: number | undefined): string;
    getWithTargetAndPercent(id: string, content: Content, threshold: number | undefined): string;
    getWithTargetAndElementTargetWithPercent(id: string, content: Content, element: string, threshold: number | undefined): string;
    getWithTargetAndElementTargetWithCountDown(id: string, content: Content, element: string, threshold: number | undefined): string;
    getWithTargetAndCountAndPercent(id: string, content: Content, count?: number, threshold?: number): string;
    getWithTargetAndCount(id: string, content: Content, count?: number): string;
    getWithTargetAndConstraintAndPercent(id: string, content: Content, groups: Array<string>, param4: boolean, threshold: number | undefined): string;
    getWithTargetAndConditionTargetAndPercent(id: string, content: Content, condition: DuringTrigger | InstantTrigger | DuringContent | InstantContent, threshold: number | undefined, param5: boolean): string;
    getWithTargetAndConditionTarget(id: string, content: Content, condition: DuringTrigger | InstantTrigger | DuringContent | InstantContent, param4: boolean): string;
    getWithTargetAndConditionShareWithPercent(id: string, content: Content, condition: string, threshold: number | undefined): string;
    getWithTarget(id: string, content: Content): string;
    getWithStrengthCountUp(id: string, threshold?: number): string;
    getWithStrengthCountDown(id: string, threshold?: number): string;
    getWithStrengthCount(id: string, threshold?: number): string;
    getWithSecond(id: string, second: number | undefined): string;
    getWithPercentAndLevel(id: string, num: number | undefined, level: number | undefined): string;
    getWithPercent(id: string, num?: number): string;
    getWithParameterReferenceTargetAndPercent(id: string, parameter: string, param3: Content, threshold: number | undefined): string;
    getWithParameterReferenceAndPercent(id: string, parameter: string, threshold: number | undefined): string;
    getWithIndex(id: string, param2: number): string;
    getWithElementTargetWithPercent(id: string, element: string, threshold: number | undefined): string;
    getWithElementTargetWithCountDown(id: string, element: string, threshold: number | undefined): string;
    getWithElementTarget(id: string, element: string): string;
    getWithElementParameterReferenceTargetAndPercent(id: string, element: string, parameter: string, content: Content, threshold?: number): string;
    getWithElementParameterReferenceAndPercent(id: string, element: string, parameter: string, threshold?: number): string;
    getWithCountAndPercent(id: string, count?: number, threshold?: number): string;
    getWithCount(id: string, count?: number): string;
    getWithConstraintAndPercent(id: string, group: Array<string>, param3: boolean, threshold?: number): string;
    getWithConstraint(id: string, group: Array<string>, param3: boolean): string;
    getWithConditionTargetAndPercent(id: string, param2: InstantContent | DuringContent | InstantTrigger | DuringTrigger, threshold: number | undefined, param4: boolean): string;
    getWithConditionTarget(id: string, param2: InstantContent | DuringContent | InstantTrigger | DuringTrigger, param3: boolean): string;
    getWithConditionShareWithPercent(id: string, param2: string, threshold: number | undefined): string;
    getPartyConditionTarget(id: string, param2: InstantContent | DuringContent | InstantTrigger | DuringTrigger): string;
    getContentTriggerLimit(param1: InstantTrigger): number | undefined;
    getContentDuringTriggerLimit(param1: DuringTrigger): number | undefined;
    getCharacterCountUpUiString(param1: number | undefined): string;
    getCharacterCountUpMinimalUiString(param1: number | undefined): string;
    getUiString(id: string): string;
}
